### ISSUE TITLE
problem with 1.11.0

### ISSUE THREAD

**Issue by b4zz4** [DanielSWolf/rhubarb-lip-sync#103]
Arch GNU/Linux

```
	mkdir build
	cd build
	cmake ..
	make rhubarb
```

```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

[...]

hubarb-lip-sync-master/rhubarb/src/tools/exceptions.cpp: En la función ‘std::string getMessage(const std::exception&)’:
rhubarb-lip-sync-master/rhubarb/src/tools/exceptions.cpp:9:17: error: ‘rethrow_if_nested’ no se declaró en este ámbito
    9 |                 rethrow_if_nested(e);

```

**Comment by DanielSWolf** [comment]
Your description is a bit sparse. So I'm guessing you're receiving this error trying to compile Rhubarb from source. What C++ compiler (exact version) on what OS are you using?

**Comment by b4zz4** [comment]
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

/home/bazza/src/aur/rhubarb-lip-sync/src/rhubarb-lip-sync-1.11.0/rhubarb/src/tools/exceptions.cpp: In function 'std::string getMessage(const std::exception&)':
/home/bazza/src/aur/rhubarb-lip-sync/src/rhubarb-lip-sync-1.11.0/rhubarb/src/tools/exceptions.cpp:9:17: error: 'rethrow_if_nested' was not declared in this scope
    9 |                 rethrow_if_nested(e);
      |                 ^~~~~~~~~~~~~~~~~
make[3]: *** [rhubarb/CMakeFiles/rhubarb-tools.dir/build.make:76: rhubarb/CMakeFiles/rhubarb-tools.dir/src/tools/exceptions.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/bazza/src/aur/rhubarb-lip-sync/src/rhubarb-lip-sync-1.11.0/rhubarb/src/tools/ProgressBar.cpp: In member function 'void ProgressBar::updateLoop()':
/home/bazza/src/aur/rhubarb-lip-sync/src/rhubarb-lip-sync-1.11.0/rhubarb/src/tools/ProgressBar.cpp:43:35: error: 'sleep_for' is not a member of 'std::this_thread'
   43 |                 std::this_thread::sleep_for(animationInterval);
      |                                   ^~~~~~~~~
make[3]: *** [rhubarb/CMakeFiles/rhubarb-tools.dir/build.make:146: rhubarb/CMakeFiles/rhubarb-tools.dir/src/tools/ProgressBar.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:366: rhubarb/CMakeFiles/rhubarb-tools.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:525: rhubarb/CMakeFiles/rhubarb.dir/rule] Error 2
make: *** [Makefile:293: rhubarb] Error 2
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by DanielSWolf** [comment]
Just merged the fix to `master`. Nice to learn that you maintain a Rhubarb package for Arch Linux; I didn't know there was one!
