### ISSUE TITLE
Unable to execute script at line 136 & does not have a value

### ISSUE THREAD

**Issue by dlewyb** [DanielSWolf/rhubarb-lip-sync#105]
When trying to run the Rhubarb Lip Sync.jsx in AE I get this error:
Unable to execute script at line 136 & does not have a value
macOS Big Sur (11.4)
AE 17.7
AE 18.4.1

**Comment by DanielSWolf** [comment]
Are you certain you copied the error message verbatim? "& does not have a value" doesn't seem to make sense to me.

**Comment by DanielSWolf** [comment]
Don't reply via e-mail! Just reply at <https://github.com/DanielSWolf/rhubarb-lip-sync/issues/105>!

**Comment by dlewyb** [comment]
what solution?

**Comment by dlewyb** [comment]
but your script still doesn't work.

**Comment by DanielSWolf** [comment]
@dlewyb Creating a duplicate issue won't get you anywhere.

The simple fact of the matter is that I closed this issue not because I consider it solved, but because I didn't wish to interact with you any more. I maintain Rhubarb Lip Sync in my sparse free time, without any compensation. You obviously can't be bothered to learn how to use GibHub. Instead, you write comments like "omg this is not worth the effort I'll just use adobe animate" and "git hub sucks". This is why I didn't feel any inclination to continue spending my time trying to help you.

**Comment by dlewyb** [comment]
Thanks for getting back to me. I only go to github except to get useful
scripts / apps to help improve work, not to communicate, I have replying
to this via email.
I am happy to pay for these useful helpers as I often do from AE Scripts. I
have even commissioned several bespoke scripts by the likes of Dan Ebberts
(not fee and not cheap) for previous national broadcaster here in Australia.
As someone who creates things myself, including some basic scripting, if
something I make doesn't work I would want to know about it to be able to
fix it.
Git Hub is not the best platform for communication, and if it lets you
close an issue that is not fixed then I think it's not very good at all.
The work I do is littered with frustrations... mostly Adobe's terrible
products which are generally propped up by third party additions. When I am
working under pressure to deliver quality outputs using less than ideal
software tools I get frustrated. I get frustrated when things don;twork as
they should and when programmers don't consider their users. This attitude
leads to the worst kind of software, of which there are plenty of examples
- um most of Adobe's offerings.
Also why are you interacting with me new if you didn't want to interact
with me anymore?
More to the point, why doesn't your script work?
Do you want me to have a look at it? Feel free to send me your code.
BTW, I was able to complete my three lip sync animation videos for Toyota
several weeks ago, so I didn't miss your script in the end.
Although it would be good to have lipsync within AE, so you should try to
get your script to work.
