### ISSUE TITLE
Support for Spine Skin Placholders?

### ISSUE THREAD

**Issue by bencresty** [DanielSWolf/rhubarb-lip-sync#108]
Hi,

First of all, thanks a lot for all the hard work and the magnificant outcome! Great tool!

I'm testing this for usage with Spine now and see everything works fine with having slots which contain region attachments/images. But some files here work with Skins, so instead of using region attachments directly into slots, they use Skin Placeholders (see: http://esotericsoftware.com/spine-skins). But unfortunately the tool doesn't recognise them so we can't use the tool on skinned files :(

Like so:
![image](https://user-images.githubusercontent.com/69322733/142032229-93639e2f-45dd-4a36-a09f-e929c643e552.png)

Or like so:
![image](https://user-images.githubusercontent.com/69322733/142032895-681db998-90eb-4d08-bc2d-945f853f03f8.png)

Which both don't get detected unfortunately:
![image](https://user-images.githubusercontent.com/69322733/142032639-95235f26-1b06-4def-b4ce-78e1cdd3be50.png)

Using version: Rhubarb for Spine 1.11.0

Any chance support for skin placeholders could make it to the project so we can also use the tool for skinned projects?

Thanks in advance and keep up the great work!

**Comment by DanielSWolf** [comment]
I'm not an active Spine user myself and I don't have experience with skin placeholders. Could you attach a zip file with a working example setup?

**Comment by bencresty** [comment]
@DanielSWolf Of course. I just created two zip files for you;

1. without-skin-folders.zip
2. with-skin-folders.zip

1)
The first one has two skins which are placed directly into the skins node. Both skins have their own folder directly inside the img-folder.

2)
The second one has the same two skins, but now these are placed inside a skin folder in Spine. This skin folder ('characters'), which is basically a skin group,  is also present as a fysical folder inside the img folder in the project. And that 'characters'-folder contains both skin-folders ('char1' and 'char2').
The concept of skin folders is created in Spine to mix-and-match different skins (of different skin folders) together at the same time, so that we can have a skin folder with mouths and a skin folder of backpacks, shoes etc. for example.

I included a short audio file with some speech I found on youtube for you to test with. Don't pay much attention to the mouth. I just created something in a hurry and I'm new to that 6-mouths rule so not sure if I did this right. But it's only for testing.
Next to the spine file I also exported the json just in case you don't have the latest spine version to export. (It's created this with Spine 4.0.47 pro btw)

Hope this makes sense and it's something you can work with! 

Thanks a lot for your willing to help! Really appreciate it! Would be very cool to use your tool with the placeholders!

If you have any questions please let me know.

Have a nice day!

[with-skin-folders.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/7549626/with-skin-folders.zip)
[without-skin-folders.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/7549625/without-skin-folders.zip)

**Comment by DanielSWolf** [comment]
Thank you for sharing your project files and for the detailed explanation! I don't have much time at the moment, so I can't promise when I'll be able to look into it. But I certainly will!

**Comment by bencresty** [comment]
Hi @DanielSWolf , thanks for the update. No problem and no hurries. Thanks for willing to make the adjustment later! Really appreciated! Have a nice weekend

**Comment by DanielSWolf** [comment]
I've attached a .zip file that attempts to add support for skinning. The content is a drop-in replacement for the original .jar file. Could you give it a try and tell me whether it works for you?

[rhubarb-for-spine-1.11.0.jar.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/7576073/rhubarb-for-spine-1.11.0.jar.zip)

**Comment by bencresty** [comment]
@DanielSWolf Wow! That's quick. Thanks!

I've just tested the new version with both test projects using skins (the ones I'd sent you). I see the lipsyncing working fine after conversion with the new jar-file, and the animations work on both skins, so that's cool!

However, when testing the new version with a file without using skins for mouths these mouths won't be recognized by Rhubarb anymore.

Not sure if the new version is just for testing only the skinned method or should be a beta version supporting both? If the first case is going on and you need help, please let me know. Perhaps I can help you in supporting both together.

It might also be good to know that when we are using skins in Spine not all slots suddenly got to have skinned slots. Some slots are still just 'regular' slots which don't change when switching to another skin.

**Comment by DanielSWolf** [comment]
Thanks for your feedback! The problem with Rhubarb for Spine is that I never took the time to write automated tests. So any change I introduce may break existing functionality, which seems to be the case here. I'll look into it and get back to you.

**Comment by bencresty** [comment]
@DanielSWolf  no worries. I'm already glad you are taking the time to make this work! Thanks again

**Comment by DanielSWolf** [comment]
> However, when testing the new version with a file without using skins for mouths these mouths won't be recognized by Rhubarb anymore.

I can't reproduce this behavior. I just loaded an old JSON file without skins into the new version of Rhubarb for Spine. The mouth slot and its attachments were all detected correctly.

Could you attach a project (ideally including the exported JSON file) that isn't working for you?

**Comment by bencresty** [comment]
Hi @DanielSWolf , I think that version is working when either having everything WITH skins or everything WITHOUT skins, but not when using both methods in the same file (so some parts skinned and other parts unskinned).

I'm having a tight deadline here, so am not able to provide you with a file which is using both methods at the same time, but if I find more time I'll provide you with one.

But perhaps and hopefully this is already useful information for you to get you started.

Thanks again for your efforts!

**Comment by bencresty** [comment]
@DanielSWolf  Sorry for the late response. Today I finally got more time, so I did some tests again with the test version of Rhubarb you sent here and create projects for you to test with.

## I've created and tested the following projects

- **no skins** (nothing skinned. No skins available)

- **fully skinned** (everything is skinned, including mouth and images inside subfolders for each skin)
- **fully skinned - no skin folders** (same as project fully skinned, but all images in the root of the images folder with a prefixed name for skinned images)

- **skinned except for mouth** (everything is skinned, excluding the mouth with is always the same. skin images inside subfolders for each skin)
- **skinned except for mouth - no skin folders** (same as Project skinned except for mouth project, but all images in the root of the images folder with a prefixed name for skinned images)

---

Without even starting the Rhubarb action, when importing the json files it's clear when Rhubarb does and when it doesn't work, just by drag'n'dropping the json onto the app. These are the results:

No skins:
![rhubarb-import-noSkins](https://user-images.githubusercontent.com/69322733/147477570-83080c48-d71f-4700-9817-b036bb0ecc50.png)

Full skinned:
![rhubarb-import-fullSkinned](https://user-images.githubusercontent.com/69322733/147477454-ca2632e5-dd4c-4cb2-ae22-cbefd945468b.png)

Full skinned - no skin folders:
![rhubarb-import-fullSkinned-no-skin-folders](https://user-images.githubusercontent.com/69322733/147477530-df5bd0f1-ce75-441a-bc58-1a3e8fee2178.png)

Skinned, except for mouth:
![rhubarb-import-skinnedExceptMouth](https://user-images.githubusercontent.com/69322733/147477611-7837e08a-0083-4672-940f-afa8762536b3.png)

Skinned, except for mouth - no skin folders:
![rhubarb-import-skinnedExceptMouth-no-skin-folders](https://user-images.githubusercontent.com/69322733/147477629-4749539d-2a33-4ebe-848e-418f463f2a96.png)

---

## test-projects

[new-rhubarb-tests.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/7780423/new-rhubarb-tests.zip)

----

## conclusion

I didn't test what happens if the mouth is skinned, but the rest is not, but my guess is that that would work, because in that case Rhubarb probably detects there are skins available and that the files for the mouth are available via these skins.

The test app works when either everything is skinned, or nothing is skinned and there are no skins used. When everything is skinned, except for the mouth, Rhubarb can't retreive the mouth parts from the json.

Hope this helps!

**Comment by DanielSWolf** [comment]
Thank you so much for going to the trouble of creating all these demo files! This will make my job much easier. I'll try to get to it as soon as I can!

**Comment by bencresty** [comment]
Hi @DanielSWolf , by no means I want to hurry you, as we're all busy so I completely understand it if you don't have the time for it. But it's two months later so I am a little curious to see if there perhaps is any progression on this? Thanks and have a nice day!

**Comment by DanielSWolf** [comment]
Wow, I didn't realize it had been so long! I'll try and fix the problem in the next few days.

**Comment by DanielSWolf** [comment]
I think I got it working in all cases. I tried out your example projects and they all look good. I've attached the zipped JAR file again. Could you give it a try before I make an official release?

[rhubarb-for-spine-1.11.0.jar.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/8135546/rhubarb-for-spine-1.11.0.jar.zip)

**Comment by bencresty** [comment]
> Wow, I didn't realize it had been so long! I'll try and fix the problem in the next few days.

Yeah, I had the exact same feeling. Time is moving way too quickly!

> I think I got it working in all cases. I tried out your example projects and they all look good. I've attached the zipped JAR file again. Could you give it a try before I make an official release?

Great news! I will. Didn't have the time for it yet, but come back to you soon on this. For now, have a nice weekend!

**Comment by bencresty** [comment]
Hi @DanielSWolf , just did a test here with all types of projects and with audio events in them. AFAIS everything works perfectly now! So it seems like a great new version to release for everybody to enjoy!

Thanks again for adjusting Rhubarb to using skins and mixtures of skinned and non-skinned elements!

**Comment by DanielSWolf** [comment]
I just released v1.12 with skinning support. @bencresty Thank you once again for your help and all the example files!
