### ISSUE TITLE
Support for Dragonbones

### ISSUE THREAD

**Issue by MasterEric** [DanielSWolf/rhubarb-lip-sync#109]
Dragonbones is a free animation software similar to Spine.

It would be very useful to have a utility similar to that for Spine, but which operates on files output by Dragonbones instead

**Comment by DanielSWolf** [comment]
I'd love to integrate Rhubarb with just about any animation tool. However, I have very little spare time, and I have decided to concentrate on the features for Rhubarb 2 for the time being.

I'm closing this issue for now, since I won't have a chance to work on it any time soon.

**Comment by MasterEric** [comment]
>  I have decided to concentrate on the features for Rhubarb 2 for the time being.

That is fair. Hope progress on it is going well!
