### ISSUE TITLE
[help]Occur "[Fatal] Application terminating with error : Error Processing file." but it is hard to find out what's the matter 

### ISSUE THREAD

**Issue by Fareastsolar** [DanielSWolf/rhubarb-lip-sync#116]
Really helpful program it is. However, I have some trouble doing this on my own pc. I follow every steps. but when I press button "Analyze Audio And Generate Animation" on  Unity3D it says "[Fatal] Application terminating with error : Error Processing file Assets/Audio/Resources/mysoundname.ogg, Error performing speech recognition via PocketSphinx tools. Could not determine path of bin Directory. ~~" like this. I checked sound file formation and directory(Assets/Audio/Resources) about a hundred times.(I mean It doesn't seems like the matter. sound file is Vorvis, 22050Hz, Mono, ogg file. and save in the Assets/Audio/Resources folder) what is the problem do you think please check this message. (error window capture posted below)
![error window](https://user-images.githubusercontent.com/110531846/182829573-3dde2e77-4641-4434-bd7d-24fbc4b48a9b.jpg)

**Comment by DanielSWolf** [comment]
You mention that you're using Unity. Rhubarb itself doesn't support Unity, so I'm assuming that you downloaded a third-party tool such as Unity-Rhubarb-Lip-Syncer.

I'm not the author of these tools, so I'm afraid I can't help you. Please contact the author of the Unity script for support.

**Comment by Fareastsolar** [comment]
I'm sorry to hear that. I confused all is same. It's my fault not even trying to know that exactly. Thank you let me know this. have a good time I will contact the Unity scripter.
