### ISSUE TITLE
rhubarb not working on Mac silicon os 

### ISSUE THREAD

**Issue by sohel-oss** [DanielSWolf/rhubarb-lip-sync#117]
<img width="1440" alt="Screen Shot 2022-09-12 at 11 19 14 PM" src="https://user-images.githubusercontent.com/112423069/189738008-01b04035-a842-4c6d-a569-51311f14c0c1.png">

sir please look at this screen shoot ... there is some file missing ,,,, im using Mac silicon os ,,, please solve that problem if possible to fixit.

**Comment by DanielSWolf** [comment]
I'm sorry, but I'm not the maintainer of the Blender plugin for Rhubarb. You'll have to contact them.
