### ISSUE TITLE
Unable to install the rhubarb.exe v1.13.0-Windows for use within Unity

### ISSUE THREAD

**Issue by coldfireagc** [DanielSWolf/rhubarb-lip-sync#119]
Hello, I am currently running in to an issue where I am unable to run the rhubarb.exe file contained within the Rhubarb-Lip-Synch-1.13.0-Windows directory. I downloaded and unzipped the latest release but when I double click the exe my taskbar flickers and then nothing happens. I feel like I am I missing something. Do I need any additional applications installed?

My goal is to use the application within Unity so I followed all the directions indicated here; https://github.com/crdrury/Unity-Rhubarb-Lip-Syncer including adding the directory to the PATH variables but I've hit a road block. 

Any assistance would be appreciated and I'd be happy to share any pertinent information. 
Thanks,

**Comment by DanielSWolf** [comment]
The behavior you describe is by design. Rhubarb is a command-line application that isn't meant to be run by double-clicking. The Unity integration you're mentioning wasn't written by me, so I can't help you there; you'll have to contact its author.
