### ISSUE TITLE
Supporting Rhubarb Lip-Sync in KorGE Game Engine

### ISSUE THREAD

**Issue by soywiz** [DanielSWolf/rhubarb-lip-sync#12]
I'm adding Rhubarb Lip-Sync (still a WIP) support to my Game Engine:
http://docs.korge.soywiz.com/audio/lipsync

And I wanted to let you now about it, and to ask a question:

Is it ok to host the binary files of Rhubarb in one of my repositories, download them with a gradle task/intelliJ plugin and run them locally to generate lipsync files from audio files?

Also, can I use those mouth images/link `Rhubarb Lip-Sync 1.0 demo` video as I'm doing in the documentation?

**Comment by DanielSWolf** [comment]
It's great to hear that you're integrating Rhubarb with your game engine! :smile: I'm currently in the process of writing integrations with major animation tools and engines, but I don't have too much free time.

Rhubarb Lip-Sync, all its resources, and all libraries it uses are under very permissive licenses. So it's perfectly fine if you host the executable in your repo, as long as you honor the license (which basically means giving credit).

It's also fine to link to any files or videos.

There is one exception: I don't own the rights to the mouth drawings I use in the documentation. Right now, I'm using them on a "Fair Use" basis, which may be legally problematic. However, I'm planning to update those images with much better drawings that I actually have the rights to within the next week or two. If you're interested, I can add a comment to this issue once I've published the new drawings; alternatively, you can follow the [Rhubarb Twitter account](https://twitter.com/RhubarbLipSync).

**Comment by soywiz** [comment]
Great :) I'm not promoting the game engine yet, and I'm still refining some edges and preparing documentation. Also have to find out how to properly embed all the sublicenses. So I think that one week or two is just ok to "legalize" everything. Thanks for replying!

**Comment by soywiz** [comment]
One more request: Could you provide a high quality sample voice file that would be free to distribute along mouth shape images? That would be awesome :) I want to create a video showing the integration with Rhubarb Lip Sync, and it would be very helpful.

**Comment by DanielSWolf** [comment]
Sure, I can do that!

**Comment by DanielSWolf** [comment]
I just updated the mouth drawings in the Readme file. Feel free to use them for your documentation!

I also just sent you an email with a short recording. However, I'm planning to release a new version of Rhubarb Lip-Sync in a few days that will visibly improve the animation quality. So it would be great if you could wait until then before creating a demo video!

**Comment by soywiz** [comment]
Perfect. Got the mail. Also, I will wait for the next version. No rush. Thanks for all!

**Comment by DanielSWolf** [comment]
I just published Rhubarb 1.5.0.

I'm closing this issue since there is nothing left for me to do here. :smile:
