### ISSUE TITLE
Rhubarb Lip Sync.jsx failing in After Effects

### ISSUE THREAD

**Issue by LandGrabber** [DanielSWolf/rhubarb-lip-sync#122]
Attempting test animation in After Effects 21.1.0 on MacOS Ventura 13.1.

Rhubarb successfully creates animation files when run from terminal but not managed to get it working from Rhubarb Lip Sync.jsx  in After Effects. The target folder is current set as /  - I don't know how to change that.

Any help would be appreciated.

Terminal Output:

Last login: Wed Jan 25 14:26:21 on ttys000
r.j.land@RJs-MacBook-Pro ~ % /usr/local/bin/rhubarb --dialogFile '/private/var/folders/p9/0cxx1wjn73xd5d5ksvb0whjm0000gn/T/TemporaryItems/e3ab5700-b211-488e-bb9b-966974ddb3b2.txt' --recognizer pocketSphinx --exportFormat json --extendedShapes '' --logFile '/private/var/folders/p9/0cxx1wjn73xd5d5ksvb0whjm0000gn/T/TemporaryItems/e3ab5700-b211-488e-bb9b-966974ddb3b2.log' --logLevel fatal --output '/private/var/folders/p9/0cxx1wjn73xd5d5ksvb0whjm0000gn/T/TemporaryItems/e3ab5700-b211-488e-bb9b-966974ddb3b2.json' '/Users/r.j.land/Documents/audiovisualism/Visual_Music/test_audio.wav'
Generating lip sync data for /Users/r.j.land/Documents/audiovisualism/Visual_Music/test_audio.wav.
Progress: [--------------------]   0%  
[Fatal] Application terminating with error: Error processing file /Users/r.j.land/Documents/audiovisualism/Visual_Music/test_audio.wav.
Error reading file /private/var/folders/p9/0cxx1wjn73xd5d5ksvb0whjm0000gn/T/TemporaryItems/e3ab5700-b211-488e-bb9b-966974ddb3b2.txt.
ios_base::clear: unspecified iostream_category error
Progress (cont'd): [--------------------]   0% %                                r.j.r.jr.j.r.j.r.j.r.r.r.rrr.r.j.lr.j.land@r.j.land@r.j.land@r.j.lanr.j.r.j.r.jrrrr.jr.jr.j.r.j.r.jr.rrrrr.rrr.rrr.rr.rrrrrrrr.r.rrrrrr.j.land@RJs-MacBook-Pro ~ %

**Comment by LandGrabber** [comment]
I've now discovered the fix for this issue by Alexey Yushkovco in the fork yushkovco/rhubarb-lip-sync. Rhubarb Lip Sync-OSX.jsx seems to works perfectly. Thank you Daniel and Alexey! Great work!

**Comment by flyingdoor** [comment]
hey, i met this problem too , my AE version is 23.5.0. 
and the folk (yushkovco/rhubarb-lip-sync) @LandGrabber   mentioned  Can not find now. 
![image](https://github.com/DanielSWolf/rhubarb-lip-sync/assets/8807037/cfac733d-9b9b-4c77-9050-9fb1c5878efd)
