### ISSUE TITLE
Unable to download for mac os (still shows as exec file) 

### ISSUE THREAD

**Issue by 19CJ2000** [DanielSWolf/rhubarb-lip-sync#123]
Hey I've tried downloading both versions 12 and 13 of rhubarb on my mac to auto lip-sync on open toonz, but every time i download it from the mac link, it provides the file in exec which cant be opened by anything other than the "Terminal" application. Any help would be greatly appreciated

**Comment by DanielSWolf** [comment]
I suspect that that's exactly how it should be. Rhubarb is not a visual application, but a command-line application. You start it by calling it from the terminal, providing information by typing it. I realize that's not ideal for users without a strong technical background, but that's all there is at the moment.

**Comment by LoganParker** [comment]
> Hey I've tried downloading both versions 12 and 13 of rhubarb on my mac to auto lip-sync on open toonz, but every time i download it from the mac link, it provides the file in exec which cant be opened by anything other than the "Terminal" application. Any help would be greatly appreciated

@DanielSWolf is correct - the executable file will not run on Mac. You need to download the [MacOS release](https://github.com/DanielSWolf/rhubarb-lip-sync/releases/tag/v1.13.0), unzip it and then you can use the exec file via your command line to run rhubarb.

`
cd path/to/your/folder
./ rhubarb [your command parameters here]
`
