### ISSUE TITLE
[FEATURE REWUEST] Live printing of visemes

### ISSUE THREAD

**Issue by madhephaestus** [DanielSWolf/rhubarb-lip-sync#126]
As a user of this program it would be relay useful for there to be status updates with the detected visemes as the program detects them. 

I am using this program to lip-sync generated speech in a robot. I want the interaction to be time-synchronus. Running through an entire execution of the program means i have to wait for all of the processing to complete. If i got a status update of the first detected viseme, i could kick off the animation thread then, instead of waiting for the complete execution. Then i would be able to read in the status updates with the additional visemes as the audio and animation was beginning to play. 

I would love a simple flag to enable this, like verbose status or something like that. I would also be willing to help add this feature, if you can point me to where i might best begin with something like this? 

This is an excellent project, thank you for all your hard work!

**Comment by DanielSWolf** [comment]
I'm closing this as out of scope; see https://github.com/DanielSWolf/rhubarb-lip-sync/issues/95#issuecomment-1593205876.
