### ISSUE TITLE
Error message saying "Check executable path in addon preferences"

### ISSUE THREAD

**Issue by ghost** [DanielSWolf/rhubarb-lip-sync#130]
Hi I'm not good with computers, I tried to click to start syncing the mouths to the audio, but it gives me a "Check executable path in addon preferences". It says the Rhubarb Executable is not found in the Library/Application Support/Blender/3.5/scripts/addons/blender-rhubarb-lipsync/bin/rhubarb.

I don't know what that means or how to fix it.

**Comment by DanielSWolf** [comment]
I'm very sorry for the late reply. This seems to be a problem with the Rhubarb plugin for Blender, which was written by a different person, so I'm afraid I can't help you.
