### ISSUE TITLE
[Fatal] Application terminating with error: Error processing file audio.wav.

### ISSUE THREAD

**Issue by NikitaFilipchuk** [DanielSWolf/rhubarb-lip-sync#132]
Apple M1 Pro Ventura Version 13.4.1 (c) . I don't understand why your lib thinks that my files have "." in the end of the file??? I have name "audio.wav" but when I try to do something with this lib it says "[Fatal] Application terminating with error: Error processing file audio.wav. Unknown file format. Only WAVE files are supported."  Is it a joke?)

**Comment by BrajBliss** [comment]
Facing the same issue. Is there a solution since this was closed? @NikitaFilipchuk
