### ISSUE TITLE
Small Platforms and Speed of Translations

### ISSUE THREAD

**Issue by marcwolf1960** [DanielSWolf/rhubarb-lip-sync#14]
Hi.
A couple of questions.
Firstly - would this run on a RPi 3 or smaller.
Secondly can this be run in a continuous speech environment.

I am looking at ways to implement this in a real time environment where an 'actor' is wearing a mascot style costume that has servo's around the characters lips. When the actor speaks the suit's mouth  will give an approximate shape of the spoken sound.

Many many thanks
Dave

**Comment by DanielSWolf** [comment]
Rhubarb should build and run fine on any Raspberry Pi. However, Rhubarb does not support continuous processing. And it wouldn't be easy to change that:

* Several processing steps require a buffer of several seconds into the future. Changing that would deteriorate the quality of the resulting animation.
* The entire architecture would have to be changed.
* The recognition and alignment process is rather CPU-hungry. I'm not sure whether it would run in real-time in a Raspberry Pi.
