### ISSUE TITLE
Features I think would be great

### ISSUE THREAD

**Issue by ghc198** [DanielSWolf/rhubarb-lip-sync#147]
"TH" Extended Mouth Shape, and the ability to control the minimum amount of frames the mouth shapes are visible for (I'm pretty sure its two frames by default in 24 fps, and it makes it look choppy).

Hope to see these features in Rhubarb 2.0!

**Comment by DanielSWolf** [comment]
The "TH" mouth shape is definitely coming in Rhubarb 2 (though I dare not guess when 🙈). Regarding the duration for mouth shapes: I have a much better algorithm in mind that should reduce the "choppiness", but that's also for Rhubarb 2.
