### ISSUE TITLE
Rhubarb not supporting .wav files

### ISSUE THREAD

**Issue by bhuvanweb3** [DanielSWolf/rhubarb-lip-sync#148]
I have runned this command "rhubarb -f json -o {output_file} {audio_file}"
 and I am getting this error.
 "Error converting audio to JSON: Generating lip sync data for data/temp_1234.wav.
Progress: [--------------------]   0%  
[Fatal] Application terminating with error: Error processing file data/temp_1234.wav.
Could not open sound file data/temp_1234.wav.
Unknown file format. Only WAVE files are supported."

**Comment by chenmosha** [comment]
You can use ffmpeg to probe the actual file format.
