### ISSUE TITLE
Mac M2 on Sonoma 14.5 Build Failed

### ISSUE THREAD

**Issue by mcroswell** [DanielSWolf/rhubarb-lip-sync#149]
After installing brew, cmake, boost, and such, I made some progress, but not sure how to proceed at this point.   Apparently I need to see the "Based on dependency analysis" to checked?  Maybe?

Any ideas?  Thank you in advance. -Mike

Here's the dump from the attempt:

`note: Run script build phase 'CMake PostBuild Rules' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'rhubarb' from project 'Rhubarb Lip Sync')
note: Run script build phase 'CMake PostBuild Rules' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'package' from project 'Rhubarb Lip Sync')
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'Rhubarb Lip Sync')
note: Run script build phase 'Generate extras/EsotericSoftwareSpine/CMakeFiles/rhubarbForSpine' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'rhubarbForSpine' from project 'Rhubarb Lip Sync')
note: Run script build phase 'Generate CMakeFiles/ZERO_CHECK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ZERO_CHECK' from project 'Rhubarb Lip Sync')
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Generate\ extras/EsotericSoftwareSpine/CMakeFiles/rhubarbForSpine /Users/m/rhubarb-lip-sync/build/build/Rhubarb\ Lip\ Sync.build/Release/rhubarbForSpine.build/Script-4939194B3147893679B642DF.sh (in target 'rhubarbForSpine' from project 'Rhubarb Lip Sync')
(1 failure)
`

**Comment by DanielSWolf** [comment]
It isn't really clear to me what steps you attempted. Also, my guess is that there was more error output than what you pasted. For a general build installation, see https://github.com/DanielSWolf/rhubarb-lip-sync/issues/159#issuecomment-2563962402.
