### ISSUE TITLE
Dockerfile supported?

### ISSUE THREAD

**Issue by chenmosha** [DanielSWolf/rhubarb-lip-sync#150]
Hi, there:

If anyone has successfully deployed the rhubarb-lip-sync using Docker? Thanks in advanced.

Regards,
Mosha

**Comment by iqbalutomo** [comment]
Hi @chenmosha I hope you are well, I just tried running it through docker compose and it worked. I'm using a Macbook Pro M3 which of course uses ARM64 architecture, while during the build process using Dockerfile of course Docker expects x86_64. so the solution is I added the flag `--platform=linux/amd64` to my Dockerfile: `FROM --platform=linux/amd64 golang:1.23`. Another alternative could be `docker run` adding a `--platform linux/amd64`.

if using compose make sure to configure the platform as well: 
```
services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
```

hopefully our problem is the same and hope it helps, thanks✨
