### ISSUE TITLE
How can I automate audio-to-JSON conversion instead of using command line?

### ISSUE THREAD

**Issue by abel-blue** [DanielSWolf/rhubarb-lip-sync#151]
I want to create a function that takes an audio file and a JSON file path as inputs, processes the audio to detect mouth cues, and saves the results to the specified JSON file, eliminating the need for command-line tools. How can I do that? Where are the functions that do this things inside the repository?

**Comment by mason-stafford** [comment]
Hi,
For automating:
1. Clone the project
2. Find the functions which command line was calling it
3. Create your own project and use them.
