### ISSUE TITLE
'rhubarb' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by naniding** [DanielSWolf/rhubarb-lip-sync#153]
Not an expert by any means when running through cmd, but I'm getting this error when using the rhubarb -o output.txt my-recording.wav command. I'm under the right directory and I have the correct .wav in the same directory. Not sure what the problem is? I'm sure this is an easy fix

**Comment by naniding** [comment]
Figured it out. Download the wrong .zip file :P

**Comment by naniding** [comment]
Figured it out. Downloaded the wrong .zip file :P

**Comment by MziouedDounia** [comment]
hey please can u tell me which file u downloaded ? cuz i have the same error
