### ISSUE TITLE
Strange Behavior? only some frames are showing on character

### ISSUE THREAD

**Issue by ayeshamalik6312** [DanielSWolf/rhubarb-lip-sync#156]
I am new to animating and this is my first time using Rhubarb lipsync. I'm not sure what I am doing wrong but If I manually scroll through the frames the mouth next to the capture button will show the preview, but if I click play that is idle for the most part.

Also, my character is only animated for the frames immediately after an Idle action (idle is x). I don't really understand whats wrong.

I checked my actions, and I think I set them up correctly, when I look at them individually in action editor they all look great.

Any help is appreciated!

https://github.com/user-attachments/assets/8d74db4d-06be-4256-ade3-754e16c19082

**Comment by DanielSWolf** [comment]
You seem to be using the [Blender plugin](https://github.com/scaredyfish/blender-rhubarb-lipsync) by @scaredyfish. I'm afraid I can't help you with that. I suggest you check with them.
