### ISSUE TITLE
Permission to use images?

### ISSUE THREAD

**Issue by fbcosentino** [DanielSWolf/rhubarb-lip-sync#158]
The licensing for the code and different parts seems well explained, but I didn't understand if I am allowed to use the mouth shape images (from the readme) elsewhere.

I mean these: https://github.com/DanielSWolf/rhubarb-lip-sync?tab=readme-ov-file#mouth-shapes

I'm making a Godot addon which will read the output files from rhubarb, and I'll have to teach users about the mouth shapes the same way it's explained in the readme of this repo. I'd like to use the same images and text from that section (with credits), and possibly make a demo animating a sprite using those images. Am I allowed to do so?

**Comment by DanielSWolf** [comment]
The MIT license covers not just the code, but also the images, including the mouth shape images. So it's absolutely OK for you to use them as you see fit. Thanks for crediting them to me; i appreciate that.
