### ISSUE TITLE
Extract phonemes rather than shapes

### ISSUE THREAD

**Issue by cchara11** [DanielSWolf/rhubarb-lip-sync#19]
Hello,

Very interesting project! I am trying to use a wave file to extract phonemes as well. In your project you can extract target shapes rather than phonemes. Is it possible to modify the program to support extraction of phonemes given a phoneme set (e.g. Arpabet, IPA)?

Constantinos

**Comment by DanielSWolf** [comment]
Rhubarb performs phone extraction as a first step, using ARPAbet internally. Have a look at `recognizePhones` in 'recognition/phoneRecognition.h'. This function takes an audio clip and some other arguments and returns a list of phones with timing information.

**Comment by cchara11** [comment]
Hello,
I am aware of this function. I tried to compile the project though with windows but didn't succeed. Tried both windows and linux, with CMake and boost 1.54/1.55. Is there any specific version needed? Are there any additional dependencies?

**Comment by DanielSWolf** [comment]
Now I'm confused. If your are aware of function `recognizePhones`, why did you ask the question in the first place?

Regarding building: Rhubarb should build fine on all major operating systems with all major compilers and all Boost versions from 1.54 upwards. There are no prerequisites beside Boost and CMake. If you're having trouble, please give me more information:

* What specific combination of OS, compiler, CMake version, and Boost version did you try?
* What error message did you get?

**Comment by cchara11** [comment]
Hello, 
I have tested in on Windows 10, CMake 3.9.1 and boost 1.54 & 1.55. 

I am getting this error:
CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:771 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:70 (find_package)

I also tried to specify the boost root directory as well as the boost libraries directory as someone suggested when googling this up. Yet, the same error appeared.

PS. I discovered the specific function after the answer.

**Comment by DanielSWolf** [comment]
I'm sorry but I can't find any error in your message. To me, this looks like a warning.

Try running `package-win.bat` and paste any error output here.

**Comment by cchara11** [comment]
I am getting the same warnings. I guess there is something wrong with the boost installation

**Comment by DanielSWolf** [comment]
Let me repeat: A *warning* is usually not an *error*. Do you get any actual errors?

**Comment by cchara11** [comment]
I know but I think the project does not compile because of these warnings. I also get this error:

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1903 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:70 (find_package)

**Comment by DanielSWolf** [comment]
I'm closing this issue because I feel that it is resolved. Should you have additional questions, feel free to comment again or to create a new issue.
