### ISSUE TITLE
How to build the project in linux system

### ISSUE THREAD

**Issue by amu340** [DanielSWolf/rhubarb-lip-sync#26]
Hi, I would like to use rhubarb to extract the mouth shape on the real time audio stream, but I don't know how to do this? I have downloaded the source code, but I can find the Makefile. How can I build the project by myself.

**Comment by DanielSWolf** [comment]
Rhubarb is CMake-based. You'll need CMake, Boost, and a C++14-compliant compiler. Then it's just the usual CMake build process.

If you're unfamiliar with CMake, read the file `package-osx.sh`; all you'll have to change is the name of the generator (the `-G` option).

**Comment by DanielSWolf** [comment]
I only just saw that you mention real-time. Rhubarb is not capable of real-time mouth animation; see issue #22.

**Comment by IzharKayani** [comment]
If you're unfamiliar with CMake, read the file package-osx.sh; all you'll have to change is the name of the generator (the -G option).

Can you please specify what to write here ?

**Comment by DanielSWolf** [comment]
@IzharKayani: That depends on what compiler/IDE you want to use. See the [official CMake documentation](https://cmake.org/cmake/help/v3.10/manual/cmake.1.html) for the `-G` option and its possible values.
