### ISSUE TITLE
GMOCK is required?

### ISSUE THREAD

**Issue by whatisor** [DanielSWolf/rhubarb-lip-sync#3]
As I know, GMOCK is only for Test purpose.
When I uncheck it from cmake, cmake configure always is error.
CMake Error at CMakeLists.txt:97 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock

**Comment by DanielSWolf** [comment]
I'm not sure what you mean by "uncheck it from cmake". If you're talking about a CMake GUI, better edit CMakeLists.txt by hand. GUIs expose only a fraction of CMake's functionality.

Yes, Google Test is only used for unit tests. If you want to remove it from CMake, you must remove the unit test project, Google Test, and all references to it. But why would you want to do that?
