### ISSUE TITLE
How to tweak the results?

### ISSUE THREAD

**Issue by gq-omistarz** [DanielSWolf/rhubarb-lip-sync#32]
This is an awesome project. Great work!

You've stated that you're getting about 75% accuracy, That means that at least 25% are still inaccurate. How do you tweak those manually? To modify the output files by hand is tedious and error-prone. Do you have a GUI for that?

Cheers

**Comment by DanielSWolf** [comment]
Rhubarb doesn't come with a GUI for tweaking animation results. Usually, however this isn't a problem:

First, 75% accuracy doesn't mean that the remaining 25% of the animation look wrong. Small inaccuracies in word recognition often don't have any visual impact on the resulting animation.

Second, Rhubarb integrates with Adobe After Effects, Magix Vegas, and (soon) Esoteric Software Spine. Depending on your requirements, you can export an animation to one of these tools, then tweak them there.

**Comment by gq-omistarz** [comment]
I see, thanks for the info. Well I need the output data in my game, so I can't use one of said programs, since they're not able to reexport a JSON file for example. Guess I will build my own little GUI based on Papagayo. Simply to move the time points around in a more comfortable way ;)

**Comment by DanielSWolf** [comment]
Sounds good. It's been a long time since I tried Papagayo. From what I remember, it doesn't really support tweaking mouth shapes, only phonemes. But my memory may be wrong.

I'm closing this issue for now, since there is nothing for me to do here. Let me know how Papagayo works out for you!
