### ISSUE TITLE
Linux documentation

### ISSUE THREAD

**Issue by jeffinrp** [DanielSWolf/rhubarb-lip-sync#39]
Hi can you please let us know how to use this in linux , i tried running the executable in linux ubuntu , but its not working ,

**Comment by DanielSWolf** [comment]
Rhubarb should run fine on Ubuntu. In order to help you, I need more information:

* What version of Ubuntu are you using?
* What version of Rhubarb are you using?
* Did you build the executable yourself or download the zip file?
* What command did you execute?
* What was the exact output?

**Comment by jeffinrp** [comment]
Hi it worked in UBUNTU. so i placed in cloud, but it didn't work on cloud

version - amazon linux
rhubarb version latest 1.7.2
i downloaded linux zip for that
./rhubarb -f json -o output.json mysound.wav
the output was following



./rhubarb: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./rhubarb)
./rhubarb: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./rhubarb)
./rhubarb: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./rhubarb)

**Comment by DanielSWolf** [comment]
Seems like the AWS server is missing the C++ standard library. As suggested by [this comment](https://stackoverflow.com/a/29263413/52041), try installing it manually.

**Comment by jeffinrp** [comment]
Unfortunately apt-get doesn't work with amazon linux , and the latest glib version it has is only 2.17
as per the following link
https://aws.amazon.com/amazon-linux-ami/2017.03-packages/

**Comment by DanielSWolf** [comment]
I just had a look at my build scripts. The Windows build [explicitly uses a static runtime](https://github.com/DanielSWolf/rhubarb-lip-sync/blob/master/rhubarb/CMakeLists.txt#L26). If the other builds did the same, this should fix your problem. Ideally, this should require very little extra code; see [this comment](https://stackoverflow.com/a/19997068/52041).

I don't have the time to look into this, I'm afraid. But if you do and it works, I'd appreciate a pull request!

**Comment by jeffinrp** [comment]
I dont understand what do you mean by changing the code? you mean i have to change the code and rebuild it ? I dont know how to build the code , any tuts or tips?

P.S. I am a JAVA developer i have very little knowledge on C++

**Comment by DanielSWolf** [comment]
Rhubarb uses CMake as a build system. To see how to build it, just have a look at the `.travis.yml` file in its root directory. It isn't hard! The [CMake documentation](https://cmake.org/cmake/help/v3.11/) is somewhat terse but generally helpful.

Rhubarb is an open source project. Among other things, this means that it users may occasionally have to delve into its source code themselves in order to get specific cases working. I'd love to spend more time working on it, but I also have to make a living ;-).
