### ISSUE TITLE
Completion percentage stops randomly

### ISSUE THREAD

**Issue by guga2112** [DanielSWolf/rhubarb-lip-sync#46]
See image

![image](https://user-images.githubusercontent.com/22722469/46721231-c64be200-cc72-11e8-8aa7-11db7df8d0f4.png)

**Comment by DanielSWolf** [comment]
Thanks! I'll look into it.

**Comment by DanielSWolf** [comment]
Found it! For performance reasons, the progress bar is only updated 8 times per second. The code that was meant to perform one final update on completion was broken. So any progress that happened after the last update was never printed.

While I was looking for the bug, I found and fixed a number of other small inconsistencies regarding progress reporting. I'm much happier with the result!
