### ISSUE TITLE
A build with phonetic recognizer support

### ISSUE THREAD

**Issue by CustomPhase** [DanielSWolf/rhubarb-lip-sync#60]
Can we get a build with phonetic recognizer please? Latest build doesnt have that support. I tried downloading the project and building it myself, but didnt manage to get far. It kept saying there were some libraries or paths missing.

**Comment by DanielSWolf** [comment]
There'll be an official release within the next few days. I'm still finding small bugs and I want to make sure there are no showstoppers left.
