### ISSUE TITLE
Change install path

### ISSUE THREAD

**Issue by RankoR** [DanielSWolf/rhubarb-lip-sync#63]
Rhubarb binary by default is installed to `/usr/local/`. I'm pretty sure that correct location should be `/usr/local/bin/`

**Comment by DanielSWolf** [comment]
I'm not sure what you mean by "is installed to". Rhubarb comes as a binary download, which needs no installation and remains exactly where you copy it to.

**Comment by RankoR** [comment]
I mean when you compile from source with `make && sudo make install`.

**Comment by DanielSWolf** [comment]
Rhubarb is using a CMake-based build. I'm afraid I've never tried CMake in conjunction with Make. So I don't know what logic Make uses to determine the target directory.

If you are more familiar with Make than I am, feel free to submit a PR that fixes this behavior.

**Comment by RankoR** [comment]
@DanielSWolf well it seems that it is default behaviour of Cmake. That's strange behaviour but it's default. Users should add `-DCMAKE_INSTALL_PREFIX=/usr/local/bin` argument to change install location.
