### ISSUE TITLE
Segmentation fault due to modification of timeline while iterating

### ISSUE THREAD

**Issue by DanielSWolf** [DanielSWolf/rhubarb-lip-sync#65]
In `voiceActivityDetection.cpp`, the activity timeline is modified while being iterated. This results in undefined behavior. On Windows, the code seems to work; on OS X, it results in a segmentation fault. 

This may be the same bug @RankoR observed in #62.

**Comment by RankoR** [comment]
Thanks. I will test it and report if bug is still there.
