### ISSUE TITLE
Integrating other voice recognition with API

### ISSUE THREAD

**Issue by Surdok** [DanielSWolf/rhubarb-lip-sync#67]
Greetings. I'm in love with what you created :), its astounding.

Anyway i have a small suggestion, can i somehow integrate the voice recognition with the text-to-speech using google cloud? i mean this one : https://cloud.google.com/speech-to-text/docs/languages

And i can specify which letters represent what image is displayed?

**Comment by DanielSWolf** [comment]
There is currently no way to integrate a speech recognition API other than PocketSphinx. Nor is there a way to change the phoneme-to-viseme mapping.

Both are hard-coded into the software. If you know how to program in C++, you might try implementing those yourself. It might be a bit tricky, though, especially integrating Google speech-to-text.

May I ask what you are trying to do? Maybe there's a way to get there without changing the code.

**Comment by Surdok** [comment]
I thought of mapping arabic letters to images of my choice based on the recognition API of google. I might give this idea a try.

**Comment by DanielSWolf** [comment]
I see. I've been thinking about adding support for languages other than English for a while now, but that isn't easy (see #5). Have you had a look at the phonetic recognizer yet?

Anyway, good luck adding support for Arabic! Let me know how it goes!
