### ISSUE TITLE
Pocketsphinx not finding acoustic model

### ISSUE THREAD

**Issue by laice** [DanielSWolf/rhubarb-lip-sync#68]
Hi, I'm on the most recent version of OSX and the most recent downloadable binary trying to use the CLI to generate a lipsync from a Google API text to speech wav and the dialog text.
The command I'm using is:
`
rhubarb input.wav -f json -d input.dialog --extendedShapes GX
`

I'm getting this output:
`
Generating lip sync data for "input.wav".
Progress: [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef'
Progress (cont'd): [#-------------------]   6%  
[Fatal] Application terminating with error: Error processing file "1552349650_dinosaureggsoatmeal.wav".
Error performing speech recognition via PocketSphinx tools.
Error creating speech decoder.
`
From what I can tell after researching this seems to be pocketsphinx looking in the wrong location for the acoustic model. Indeed, the referenced folder doesn't exist and homebrew puts sphinx elsewhere, but I can't seem to find any way to customize the directory for rhubarb.

I also get the same output when I start the program with `-r phonetic`, which I hoped might avoid calling on the sphinx acoustic model. 

Any idea of the best way to direct rhubarb to the acoustic model's actual directory, or what else might be going on here?

**Comment by laice** [comment]
Derp, this is what happens when you remove the executable away from the "res/" directory in the install

**Comment by hitarthaGIT** [comment]
Please explain the fix...I am having the same issue.
