### ISSUE TITLE
rhubarb error exec format error in blender 2.79

### ISSUE THREAD

**Issue by roccotitlan** [DanielSWolf/rhubarb-lip-sync#70]
Hi. Trying to run rhubarb on blender 2.79 but it doesnt work. Ive created a pose library, uploaded a .wav audio file and when pressing Rhubarb lipsync button it pops the error: "OSError: [Errno 8] Exec format error"
![Screenshot from 2019-04-15 21-54-32](https://user-images.githubusercontent.com/49666421/56205836-7f1f1f00-6010-11e9-8d6d-57abe33f6af4.png)
Im Using Ubuntu 16.04.
Yes, User Preferences is correct
![Screenshot from 2019-04-16 06-02-43](https://user-images.githubusercontent.com/49666421/56205883-978f3980-6010-11e9-8830-3a8ad7ab9727.png)
No, rhubarb does not run from command line, no additional error messages, only "Exec format error"
![Screenshot from 2019-04-16 06-05-18](https://user-images.githubusercontent.com/49666421/56205924-b988bc00-6010-11e9-8e80-075abfe2d7ac.png)
No additional error messages when running Blender from command line
Thanks for advise

**Comment by DanielSWolf** [comment]
I'm afraid I can't help you. The Blender addon was written by scaredyfish, not me.

You might try reporting this issue [at his repository](https://github.com/scaredyfish/blender-rhubarb-lipsync).
