### ISSUE TITLE
Making Animations more Smooth

### ISSUE THREAD

**Issue by towfiqi** [DanielSWolf/rhubarb-lip-sync#72]
Daniel,

I Like rhubarb and very grateful to you for making it open source. But I have a gripe with it, this goes for most lips animation software actually. Anyway, here it is:

The generated animation is fine for 2d cartoon, but for 3d/realistic looking subjects, it looks like watching a stop motion animation. Because transitioning from mouth shape A to B happens instantly. This makes rhubarb very limiting. It would be great, there was an option to add more mouth shapes related to each mouth shapes so that the animation looks more smooth. 

Can the animation made more smooth if we used more mouth shapes? for example, for transitioning  from mouth shape A to B, maybe use more mouth shapes for A, for example, lips_AB1, lispAB2, lipsAB3 . Would it work? 

I am using the Spine extension. Did you write the spine extension in Java? I see that you have written the after effects extension in javascript. Since I am a javascript developer, can I modify the after effects extension to use it with Spine?

Related #28 

Thank You

**Comment by DanielSWolf** [comment]
I'm (painfully) aware that Rhubarb is currently no good fit for 3D animation. 3D animation uses key frames and smooth interpolation, whereas Rhubarb uses holds. The result, as you describe, resembles stop-motion animation. Adding more mouth shapes wouldn't solve the underlying problem. The solution, instead, would be to add a *real* 3D animation algorithm whose output are keyframes and interpolation information. At some point in the future, I may add such a mode. However, for the time being, this is out of the scope of Rhubarb. That's why I call it a tool for 2D lip-sync animation.

Regarding Rhubarb Lip Sync for Spine: Technically, this isn't an extension because Spine (regrettably) does not support extensions. Instead, it's a standalone GUI program that modifies Spine animation files. It's written in Kotlin and you can find its source code at `/extras/EsotericSoftwareSpine`. The After Effects script is written in JavaScript because that's what After Effect's scripting engine uses. While it would certainly be possible to port Rhubarb for Spine to JavaScript, this would mean a lot of work. In my experience, learning new programming languages is a great way to broaden your knowledge!

**Comment by towfiqi** [comment]
Daniel,

Thanks for your response. Although I know a little bit of Java, I really don't have time to learn a Kotlin, becuase I have to create a prototype as soon as possible, incesting my time to learn a new language will set me back a month or two.

Its great to hear the Spine program only modifies the spine json file. I can modify the json file easily with node js. My understand is, the result outputted by rhubarb command line tool:

```
0.00	A
0.05	B
0.63	C
0.70	B
0.84	F
0.98	D
```

Can be converted and added like this in the json file's animation section and it should work:

```
	"the_animtion": {
		"slots": {
			"lips": {
				"attachment": [
					{ "time": 0, "name": "lipsa" },
					{ "time": 0.5, "name": "lipsb" },
					{ "time": 0.63, "name": "lipsc" },
					{ "time": 0.70, "name": "lipsb" },
					{ "time": 0.84, "name": "lipsf" },
					{ "time": 0.98, "name": "lipsd" },
				]
			}
               }
         }
```

Is this assumption correct? Do I need to make any other changes to the json file?

And rhubarb is a little slow, I think its becuase the time pocketSphinx take to recognize the words in the audio file. In my project, I will use google speech to text, which will output a something like this:

```
[
             {
                "startTime": "1.300s",
                "endTime": "1.400s",
                "word": "Four"
              },
              {
                "startTime": "1.400s",
                "endTime": "1.600s",
                "word": "score"
              },
              {
                "startTime": "1.600s",
                "endTime": "1.600s",
                "word": "and"
              },
              {
                "startTime": "1.600s",
                "endTime": "1.900s",
                "word": "twenty"
              }
]
```
What file/function do I look into inside this repo to see how rhubarb converts the words to mouth shapes directly. I mean what function does rhubarb uses to convert words to shapes eg:

```
0.00	A
0.05	B
0.63	C
0.70	B
0.84	F
0.98	D
```

Thanks

**Comment by DanielSWolf** [comment]
Your assumption is correct. Rhubarb for Spine only adds the JSON structure you mention, and it should be easy to do the same in Node.

**Comment by towfiqi** [comment]
What I did to replace the slot attachment animation that Rhubar added, is added a 5 slots to my project, 
1. upper_lip
2.  teeth_top
3. teeth_bottom
4. mouth
5. bottom_lip

each with its own mesh attachments. Then I generated, 30 animations from one mouth shape to another. eg: AB, AC, AD, AE, AF, BA, BC, BD, BE, BF, CA, CB etc. Then exported the project to json file and then looked for the 30 animations inside the animation section, each animations had deform values, that indicated the changes from A to B , B to C etc.. like so:
```
	"B-A": {
		"deform": {
			"default": {
				"speaklips_bottom": {
					"lips_bottom": [
						{
							"time": 0,
							"vertices": [ -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -0.35825, -1.44762, -1.1517, 0, -0.867, 0.22116, -2.99332, -1.0E-5, -2.99332, -1.0E-5, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -2.03085, -1.0E-5, -1.1517, 0, -1.17065, -0.74419, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.19669, -1.57648, -2.84903, 0, -2.39487, 0, 9.0E-5, 1.31978, -3.39755, 0, -1.12668 ]
						},
						{
							"time": 0.1667,
							"vertices": [ 1.65341, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.50305 ]
						}
					]
				},
				"speaklips_top": {
					"lips_top": [
						{
							"time": 0,
							"vertices": [ 3.11328, 0, 3.11328, 0, 3.11328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0607, 3.33444, 0.39999, 2.98324, -1.10327, -3.77558 ]
						},
						{
							"time": 0.1667,
							"vertices": [ -0.42126, 0, -0.42126, 0, -0.42126, 0, -0.42126, 0, -0.42126, 0, 0, 0, -0.42126, 0, -0.42126, 0, -0.42126, 0, 0, 0, 0, 0, -0.42126 ]
						}
					]
				}
			}
		}
	},
```

What I then did was, replace the animation that rhubarb outeputted in the json file and replaced it with each A>B, B>C values manually.

So this:

```
"say_audio": {
		"slots": {
			"lips": {
				"attachment": [
					{ "time": 0, "name": "lipsa" },
					{ "time": 0.0333, "name": "lipsb" },
			}
		}
}
```
becomes this:

```
"say_audio": {
		"slots": {
		"deform": {
			"default": {				"speaklips_bottom": {
					"lips_bottom": [
						{
							"time": 0,
							"vertices": [ 1.65341, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.50305 ]
						},
						{
							"time": 0.0333,
							"vertices": [ -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -0.35825, -1.44762, -1.1517, 0, -0.867, 0.22116, -2.99332, -1.0E-5, -2.99332, -1.0E-5, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.1517, 0, -2.03085, -1.0E-5, -1.1517, 0, -1.17065, -0.74419, -1.1517, 0, -1.1517, 0, -1.1517, 0, -1.19669, -1.57648, -2.84903, 0, -2.39487, 0, 9.0E-5, 1.31978, -3.39755, 0, -1.12668 ]
						},]
				},
				"speaklips_inner": {
					"mouth_inner": [
						{ "time": 0 },
						{
							"time": 0.1667,
							"vertices": [ 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.3934, 3.55001, -1.88339, 3.55001, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, -0.00381, 3.55001, 0.23123, 2.59738 ]
						},
						{
							"time": 0.6,
							"vertices": [ 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.3934, 3.55001, -1.88339, 3.55001, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, 1.64072, 0, -0.00381, 3.55001, 0.23123, 2.59738 ]
						},]
				},
				"speaklips_inner_bottom": {
					"mouth_inner_bottom": [
						{ "time": 0 },
						{
							"time": 0.1667,
							"vertices": [ -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429 ]
						},
						{
							"time": 0.6,
							"vertices": [ -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -2.01035, 1.50775, -2.01035, 1.50775, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429, 0, -3.05429 ]
						}]
				},
				"speaklips_top": {
					"lips_top": [
						{
							"time": 0,
							"vertices": [ -0.42126, 0, -0.42126, 0, -0.42126, 0, -0.42126, 0, -0.42126, 0, 0, 0, -0.42126, 0, -0.42126, 0, -0.42126, 0, 0, 0, 0, 0, -0.42126 ]
						},
						{
							"time": 0.0333,
							"vertices": [ 3.11328, 0, 3.11328, 0, 3.11328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0607, 3.33444, 0.39999, 2.98324, -1.10327, -3.77558 ]
						}]
				}
			}
		}
}
```

The animation is much smoother. Output Video :
https://giant.gfycat.com/GleamingTheseArchaeopteryx.webm


Maybe this somehow can be added to Rhubarb Spine tool in future? What the user has to do is, provide is the 30 lips transition animations which is not that time consuming actually. I made the 30 animations in like 2 hours and I am not even an animator. Rhubarb can determine the deform values of each mouth transition and add them to the the json file.

Let me know, what you think.

**Comment by DanielSWolf** [comment]
That looks much smoother indeed. I do have some vague plans for 3D animation. If and when I implement that in Rhubarb, I'd like to do it properly, that is, base it on keyframes and transitions. But it will probably take me years.
