### ISSUE TITLE
Magix Vegas and rhubarb need help please

### ISSUE THREAD

**Issue by Mindslaver79** [DanielSWolf/rhubarb-lip-sync#75]
Hi,
I'm trying the latest version of rhubarb with Magix Vegas 16, have created the xml file and selected the image file, when I press OK, I get the following Error : Image file name doesn't have expected format. 
Have tried with BMP , PNG and JPG what should I do ?

Best regards

**Comment by DanielSWolf** [comment]
I'm sorry for the unspecific error message. You can use any image format you like, provided that Vegas supports it. What's important is the format of the image *names*.

All your file names must end with a hyphen ("-"), followed by the shape name. For example, *alice-a.png*, *alice-b.png*, *alice-c.png*... or *bob-a.jpg*, *bob-b.jpg*, *bob-c.jpg*... -- you get the idea.

**Comment by Mindslaver79** [comment]
Thanks a lot, that solved it for me.
