### ISSUE TITLE
Magix Vegas, any way to use rhubarb multiple times on the same project ?

### ISSUE THREAD

**Issue by Mindslaver79** [DanielSWolf/rhubarb-lip-sync#76]
Really enjoying rhubarb,
I need to use it multiple times on the same project, but everytime I import rhubarb from the scripting (Magix Vegas 16) it exits my current project and starts a new one. Any way to bypass it and have multiple instances of rhubarb running on the same project? 

Best Regards
![Untitled-1](https://user-images.githubusercontent.com/52376690/61123503-2d6e1f80-a4ad-11e9-9ecc-4d7a59ac056a.jpg)

**Comment by DanielSWolf** [comment]
There is currently no direct way of adding lip-synch'ed data to an existing project. As a workaround, you can open two Vegas windows, run the script in one, then select the result and copy it over to the other one.
