### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by malcolmcdixon** [DanielSWolf/rhubarb-lip-sync#79]
Hi Daniel,

There seems to be a virus in rhubarb.exe according to Comodo Internet Security called Trojware.Win32.Spy.Teront.DA@354509393, can you please eradicate as I'm keen to use this software.
I downloaded the Win32 version.
 Thanks.

**Comment by DanielSWolf** [comment]
I just scanned *rhubarb.exe* from version 1.10.0 using multiple other virus scanners, all of which came out clean. I couldn't find any information on Trojware.Win32.Spy.Teront.DA@354509393 that would allow me to investigate further.

My guess is that this is a glitch in Comodo's virus signature database. You could try sending them the executable for further analysis. Let me know what you find!

**Comment by masqu3rad3** [comment]
Daniel you can upload the file to virustotal.com and find out which
database triggers the false positive. Then you can send an email to the
customer service of the specific av software and claim to mark it as safe.
It usually takes less then a couple of days.

**Comment by DanielSWolf** [comment]
That's what I meant when I suggested to @malcolmcdixon to send the executable to Comodo. I'm rather pressed for time at the moment, so I can't do it myself.

**Comment by masqu3rad3** [comment]
Ok, didnt understand, sorry about that :)

**Comment by malcolmcdixon** [comment]
Hi Daniel,

 

Thanks for getting back to me so promptly.

 

I have submitted the zip file to Comodo, so I will let you know the result of their investigation.

 

As you suggest it is probably just a false positive, so I will set up an exception and proceed from there.

 

Thanks again.

 

Best regards,

 

Malcolm.
