### ISSUE TITLE
After Effects

### ISSUE THREAD

**Issue by Sugarbank** [DanielSWolf/rhubarb-lip-sync#8]
Hi do you have support for an after effects script that parses the xml to time remapped keyframes?

**Comment by DanielSWolf** [comment]
Not yet. But I've been planning to write an import script for After Effects for some time now.

I can't promise how soon I'll find time for it, but it's definitely coming. I'll update this issue as soon as there is news.

**Comment by Sugarbank** [comment]
Cheers:) Thanks mate

**Comment by Sugarbank** [comment]
any luck with the import script?

**Comment by DanielSWolf** [comment]
I've started playing with After Effect's plugin API. But I haven't devoted it much time yet.

**Comment by DanielSWolf** [comment]
I've implemented an After Effects script. It's available in Rhubarb 1.6.0.
