### ISSUE TITLE
Bundling Rhubarb Lip Sync with the Blender addon

### ISSUE THREAD

**Issue by scaredyfish** [DanielSWolf/rhubarb-lip-sync#81]
Hi, I'm Andrew the creator of the Blender Rhubarb Lip Sync addon.

I've noticed that the biggest difficulty people seem to have using my addon is that they find it hard to understand they have to install two different things.

In order to make things easier for them, I would like to bundle Rhubarb Lip Sync with the addon, so that it comes pre-configured and ready to go. My understanding is that this is already allowed under the MIT license, but I wanted to make sure you're okay with it before I go ahead. 

I'll do my best to ensure it's clear in the documentation that you are the creator of Rhubarb Lip Sync, and that I am only responsible for the Blender integration.

Let me know if this is okay. Cheers.

**Comment by Banbury** [comment]
The MIT license is pretty generous. It gives you the right to do almost anything with Rhubarb, including bundling it with your addon.

**Comment by DanielSWolf** [comment]
Hi Andrew,

Thanks for getting in touch! You are correct in that the MIT license allows you to bundle Rhubarb with your Blender plugin, and I think it's a good idea. My experience is also that people have a hard time understanding the difference between our two tools; in fact, I regularly get support issues asking for help with your plugin. Bundling Rhubarb with your plugin might make it more obvious whom to contact for Blender-related questions. (While you're at it, maybe you could add a note to that effect in your readme file).

**Comment by scaredyfish** [comment]
Thanks Daniel, will do.
