### ISSUE TITLE
windows installation error

### ISSUE THREAD

**Issue by kunalkala** [DanielSWolf/rhubarb-lip-sync#82]
Hi Daniel,
When I try to use the jar file for the Spine runtime in the extras folder on my Windows 10 machine, I get the error "Could not find the main class: com.rhubarb_lip_sync.rhubarb_for_spine.MainKt. Program will exit.".  I can use the command line on the rhubarb,.exe file, there is no problem there. however when I try to run the GUI for spine, using the rhubarb-for-spine-1.10.0.jar in the extras folder I get this error

**Comment by DanielSWolf** [comment]
This might be a problem with your Java Runtime Environment (JRE). Try installing JRE 8 from Oracle: https://java.com/en/download/win10.jsp

**Comment by kunalkala** [comment]
Yes, now it works. Thanks

**Comment by DanielSWolf** [comment]
Glad I could help!
