### ISSUE TITLE
Error with After Effects on OSX

### ISSUE THREAD

**Issue by charlielaud** [DanielSWolf/rhubarb-lip-sync#84]
Running AE 2020 on OSX 10.13.6. When I run the Rhubarb import .jsx in After Effects, I keep getting a generic error message. When I run directly from the command line, I receive this as a message: "[Error] "acmod.c", line 83: Folder '/usr/local/bin/res/sphinx/acoustic-model' does not contain acoustic model definition 'mdef' ". Looking further, there's not even a /res/ directory at /user/local/bin/ . Any idea what to do here?

**Comment by charlielaud** [comment]
/res directory included with the download needed to be placed at the /usr/local/bin/ path. Doing so resolved everything.

**Comment by DanielSWolf** [comment]
@charlielaud I'm glad it's working for you now. However, copying the *res* directory to *bin* should not be necessary. Did you follow [the instructions](https://github.com/DanielSWolf/rhubarb-lip-sync/blob/master/extras/AdobeAfterEffects/README.adoc), creating a symlink to the executable?

**Comment by charlielaud** [comment]
Hey @DanielSWolf - I assumed I had followed the instructions properly but I suppose I hadn't! I just now removed everything and re-tried it and it worked just fine. Not sure what happened. My best guess is that I accidentally copied over the executable instead of creating a symlink. Thanks for the quick response!
