### ISSUE TITLE
How to integrate the json file to THREE.js library?

### ISSUE THREAD

**Issue by rahulrajpalhiteshi** [DanielSWolf/rhubarb-lip-sync#87]
Hi there,
Thank you for this amazing app!

I'm struggling from last 3 days on how to integrate this in THREE JS app.

I've seen this video:  [](https://www.youtube.com/watch?v=vZVtUEEssxQ&t=3s) and I've imported the fbx model in THREE JS but, I didn't found any solution which will auto animate the lips as per the generated JSON file.

Please can you suggest a method or a proper solution on this.

**Comment by DanielSWolf** [comment]
I'm afraid I can't help you there. I'm happy to answer any questions you have regarding Rhubarb Lip Sync and its export formats. But I've never worked with three.js. I guess you'd have better chances asking in their community.

**Comment by rahulrajpalhiteshi** [comment]
@DanielSWolf Thank you for the update! I'll ask the community of three.js

Thank you again for the immediate response.

**Comment by smartday** [comment]
Hi, @rahulrajpalhiteshi 
I have complete lip-sync with THREE JS using JSON from this Rhubarb Lip Sync engine.
If you are still interested, please tell me.
I can help you. Regards.

**Comment by wduo** [comment]
@sayhellometaverse2022 Hi, I am very interested in that lip-sync with THREE JS using JSON from this Rhubarb Lip Sync engine . Could you please help me?
