### ISSUE TITLE
Unity 3D Support

### ISSUE THREAD

**Issue by bilck** [DanielSWolf/rhubarb-lip-sync#90]
Do you plan to add Unity 3D support as a plugin or something like that?

I see Rhubarb already has Spine support, it would be **very** nice if Rhubarb also integrated with Unity and Timeline.

**Comment by DanielSWolf** [comment]
I'm not currently adding any major features because I'm planning to rewrite Rhubarb to get rid of some of its limitations. Once I'm done with that, a Unity plugin makes total sense. But given my limited time, it will probably take years.

I'm closing this issue for the time being.
